name: Publish Release

on:
  release:
    types: [published]

jobs:
  publish-release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run docs
      - name: Publish Release ${{ github.event.release.name }}
        run: |
          PKG_VERSION=$(npm version from-git)
          export BUILD_VERSION=${PKG_VERSION/v/}
          rm -rf dist/
          npm run browserify
          npm run prepare

          # Publish to NPM
          echo 'registry=https://registry.npmjs.org' >> .npmrc
          echo '//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}' >> .npmrc
          npm publish --tag=latest --access=public
          git restore .npmrc
          echo "Release $BUILD_VERSION published to NPM."

          # Publish to GHP
          echo 'registry=https://npm.pkg.github.com' >> .npmrc
          echo '//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}' >> .npmrc
          npm publish --tag=latest --access=public
          git restore .npmrc
          echo "Release $BUILD_VERSION published to GHP."

          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add README.md package.json package-lock.json
          git status
          git commit -m":package: [skip ci] Release \`$BUILD_VERSION\` by :robot:

          Co-authored-by: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          "
          git log -n 2
          echo "Done." && exit 0
      - name: Push Version Update
        uses: ad-m/github-push-action@master
        with:
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
